### ISSUE TITLE
Data set problem when training TCQE

### ISSUE THREAD

**Issue by lbl159357** [v587su/TCQE_public#2]
Hello, when I was training TCQE, the input dataset parameter was --data_path=datasets/python_gpt2_nll_loss/. However, when I was debugging, I found that when the code ran to the 48th line in the model/dataset.py file, an error message was "Directory datasets/python_gpt2_nll_loss/train_0". Was it the problem with the dataset? Thank you very much for your help!

**Comment by v587su** [comment]
I fixed this bug. Now you can run the code.😊
