### ISSUE TITLE
Problems with generating data sets for CodeT5's TCQE

### ISSUE THREAD

**Issue by lbl159357** [v587su/TCQE_public#3]
Hello, sorry to bother you, but when I was using CodeT5 to generate a dataset for TCQE recently, the code passed the function at line 86 of the dataset.py file with a 'TypeError: 'NoneType' object is not subscriptable ', I guess it is the command parameters are different on model CodeT5? Can you publish the command to generate data sets for CodeT5's TCQE?

**Comment by v587su** [comment]
Sorry, I deprecated the experiments using CodeT5 considering that it is not very suitable for code generation. Therefore, the code for CodeT5 is no longer used and maintained. You can refer to the new version of our paper (https://arxiv.org/pdf/2209.05948.pdf) and use CodeGen instead.

**Comment by lbl159357** [comment]
Thanks for your reply!
